### PR TITLE
feat: use 1.11

### PR DESCRIPTION
**Pull request by psturc**
## Motivation
Get up-to-date with 1.11 go-client, apimachinery & codegenerator.

The only manual changes are done to [the script](https://github.com/aerogear/mobile-crd-client/compare/1.11?expand=1#diff-7dfd41fda74557e74b129ac111f3c66b)

### CODE REVIEW

**Comment by wei-lee** [comment]
@psturc now i am thinking if we actually need this repo. I believe this repo is used by UPS operator to get the type definition for the mobile client. But if we use `dep` as the dependency manager for the UPS operator, we could just point it to use mdc, and it should only use and download the `apis` dir in mdc. It will achieve the same goal, without the requirement of using this repo at all. It also means we can keep the definition of mobile client in one place.

wdyt?

**Comment by psturc** [comment]
@wei-lee I don't really understand how it works behind the scenes in Go pkg management. Your suggestion sounds good to me, but let's rather ask real experts :)
@maleck13 @darahayes

**Comment by maleck13** [comment]
@wei-lee this may be possible but you may want to look into deps support just pulling in sub packages of a project and also stripping the vendor dir from the mdc project

**Comment by wei-lee** [comment]
thanks @maleck13. @psturc in this case, let's get this one up to date first, and we can continue use it for now. We can come back to this later on. We are not going to update the crd very often anyway.

**Comment by psturc** [comment]
@wei-lee are we okay to merge this guy now?

**Comment by wei-lee** [comment]
@psturc yes. one last thing, can you please add a link to the type file to the original type file in MDC so that if anyone is going to work on this, they will know where to find the original file

**Review by wei-lee — APPROVED** [review]

**Comment by laurafitzgerald** [comment]
@wei-lee I believe @psturc is out this week and this appears to be the last pr to close for the JIRA. Can we close this one and close the task on Pavel's behalf?

**Comment by wei-lee** [comment]
@laurafitzgerald yes, I can do that.

**Pull request merged**
